linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - revive

run:
  timeout: 5m

issues:
  exclude-use-default: false
